apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
data:
  superset_config.py: |
    import os
    SECRET_KEY = os.environ.get("SUPERSET_SECRET_KEY")
    
    # Configuración adicional si es necesaria
    ENABLE_PROXY_FIX = True
    SQLALCHEMY_DATABASE_URI = os.environ.get("SQLALCHEMY_DATABASE_URI")