apiVersion: v1
kind: Secret
metadata:
  name: superset-db-uri
  namespace: superset
type: Opaque
stringData:
  SQLALCHEMY_DATABASE_URI: "postgresql://superset:PLACEHOLDER_PASSWORD@superset-database-endpoint:5432/superset"
  SECRET_KEY: "PLACEHOLDER_SECRET_KEY" 