apiVersion: v1
kind: Service
metadata:
  name: superset
  labels: { app: superset }
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8088
  selector:
    app: superset